spring:
# Profiles
  profiles:
    active: dev
# Helianto
helianto:
  contextName: DEFAULT
  root:
    system:
      ADMIN: READ,WRITE
      USER: READ
  password:
    initial: 123456
    install: h3l1@nt0
  welcome:
    logo: /images/logo-iserv64.png
    copyright: i-serv Consultoria Empresarial Ltda. 2004-2016
    inLineCss: |
      h3,h5,.footer {color: white;}
      .heliantoLogin {background-image: url('/images/photo-1434396505260-9ec0d6491795.jpeg');}
  mfa:
    cellPhone: required
    service: none

key-store:
  password: changeme
# Logging
logging:
  level:
    org.helianto: INFO
    org.springframework.security: INFO
    org.helianto.message: DEBUG