spring:
# Profiles
  profiles:
    active: dev
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

# Helianto
helianto:
  host: localhost
  mailer-host: ${helianto.host}
  db-host: ${helianto.host}
  title: Helianto Control Panel
  base-name: home
  contextName: DEFAULT
  root:
    system:
      ADMIN: READ,WRITE
      USER: READ
  user-token-validity: 5
  password:
    initial: 123456
    install: h3l1@nt0
  welcome:
    brandName: Helianto
    logo: /images/logo.png
    copyright: i-serv Consultoria Empresarial Ltda. 2004-2016
    inLineCss: |
      h2,h3,h5,.footer {color: white;}
      .heliantoLogin {background-image: url('/images/photo-1434396505260-9ec0d6491795.jpeg');}
  mfa:
    # cell phone, one of required | none
    cellPhone: none
    service: totalVoice
  register:
    # define admin option, one of ALLOW | DENY | a domain name
    admin: allow
    # define principal type, one of EMAIL | PIN  - to be implemented: | PHONE | USERNAME
    principal: email
    # pinMask: 999.999.999-99
    # public unique number may be required
    pun: required
    punMask: 99.999.999/9999-99
    contextDomain: helianto.org
    inLineCss: |
      h2,h3,h5,.footer {color: white;}
      .heliantoLogin {background-image: url('/images/photo-9240912-peq.jpg');}

key-store:
  password: changeme
# Logging
logging:
  level:
    org.helianto: INFO
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.helianto.message: DEBUG