spring:
# Profiles
  profiles:
    active: dev
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10
    name: helianto
    password: helianto
    test-on-borrow: true
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 5000
    url: jdbc:mysql://192.168.10.5:3306/helianto01?autoreconnect=true
    username: helianto
    validation-query: SELECT 1
# Spring Data JPA
  jpa:
    repositories:
      enabled: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    show-sql: false
# Server
server:
  port: 8081

# Helianto
helianto:
  contextName: DEFAULT
  defaultCountry: BR
  intialSecret: changeme
  root:
    principal: mauricio@iservport.com
    displayName: Maurício
    firstName: Maurício
    lastName: Fernandes de Castro
    entity:
      alias: DEFAULT

# Logging
logging:
  level:
    com.iservport.basic: DEBUG
    org.springframework.security: INFO

